### ISSUE TITLE
Deprecation of attributes - no longer works with 9.0.0+

### ISSUE THREAD

**Issue by BottlecapDave** [lozzd/octopus-energy-rates-card#27] opened 2023-10-09 07:39 UTC
Hello. I just wanted to inform you that I've made the attributes that this card uses [deprecated](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/discussions/444), which will be removed in the next major version (post november 6th).

I suggest this card is adapted to take a collection of entities, which the card then merges the rate data for?

**Comment by lozzd** [comment] 2023-10-09 08:41
Thanks for the head up! Do you have a new example data structure somewhere that I can check to see if I can make it work? (is that already live?)

**Comment by lozzd** [comment] 2023-10-09 13:54
Wow I totally missed the link in that message originally. pre-coffee. Will look in to it.

**Comment by lozzd** [comment] 2023-11-20 21:58
I haven't had time to look in to this so if you wish to keep using the card *do not* yet upgrade to 9.0 of the integration

**Comment by steve-prentice** [comment] 2023-11-21 11:50
"if you wish to keep using the card do not yet upgrade to 9.0 of the integration"

Oops.... :-/

**Comment by RazorClam** [comment] 2023-11-21 11:58
> "if you wish to keep using the card do not yet upgrade to 9.0 of the integration"
> 
> Oops.... :-/

Ha, same! =( 
Something else my wife used and now doesn't work! This is life on the cutting edge.
Thanks for all your work guys. Look forward to a fix

**Comment by deltamelter** [comment] 2023-11-21 12:17
There's a lot to fix in this, I took the opportunity to add some additional colours and rate bands...

I still hate the way the browser refuses to give up using the cached version of javascript cards like this one, always seem to spend most of my time trying to get changes to appear :) 

as well as the "start" all "all_rates" changes, the  card expects to be dealing in pence whereas the value is now in decimal pounds so needs to be multiplied by 100... this threw me on some of the graphs too where I was previously dividing by 100 to get GBP

**Comment by igloo32** [comment] 2023-11-21 12:28
> There's a lot to fix in this, I took the opportunity to add some additional colours and rate bands...
> 
> I still hate the way the browser refuses to give up using the cached version of javascript cards like this one, always seem to spend most of my time trying to get changes to appear :)
> 
> as well as the "start" all "all_rates" changes, the card expects to be dealing in pence whereas the value is now in decimal pounds so needs to be multiplied by 100... this threw me on some of the graphs too where I was previously dividing by 100 to get GBP

If your referencing your own version of the Javascript module you can add a version reference to the url, then you just increment it each time you update your Javascript, i.e. in the URL section do this:

/local/octopus-energy-rates-card.js?v=6

Now if you refresh the page it should force it to reload the new version

**Comment by Daverover66** [comment] 2023-11-21 13:55
> > "if you wish to keep using the card do not yet upgrade to 9.0 of the integration"
> > Oops.... :-/
> 
> Ha, same! =( Something else my wife used and now doesn't work! This is life on the cutting edge. Thanks for all your work guys. Look forward to a fix

Same here.  Also loking forward to a fix.  This will currently sit as a blank card on my dashboard.  Has anyone else noticed that the new event entity also doesn't work in apexcharts?

**Comment by deltamelter** [comment] 2023-11-21 18:27
Looks like the card will need reorganising too, because the rates are now split by day.   I thought it would just a case of renaming the array and start attribute and scaling to pence, but currently needs multiple cards... 
![image](https://github.com/lozzd/octopus-energy-rates-card/assets/27061628/56a68388-da5b-45cb-97b1-7e3ea487662d)

**Comment by igloo32** [comment] 2023-11-21 19:10
I've got a rough version working with some other bits in, need a bit of time to tidy it up but essentially you need to bring in the other 2 sensors with the past and future rates in and combine them into 1 array.
![image](https://github.com/lozzd/octopus-energy-rates-card/assets/13981093/5bbe804a-76f2-4e25-aa1b-a42120826033)

**Comment by LucidityCrash** [comment] 2023-11-22 10:53
completely unrelated but liking the Gas Tracker bit :)

**Comment by stevetrease** [comment] 2023-11-22 14:10
I've just submitted a pull request for some quick and dirty changes to support v9.0.0 of the HomeAssistant-OctopusEnergy integration.

Essentially it uses event.octopus_energy_electricity_{{METER_SERIAL_NUMBER}}{{MPAN_NUMBER}}_current_day_rates rather than the previous entity type.

It only supports one event entity, so if you want to see tomorrow's rates just use a second card with the event.octopus_energy_electricity_{{METER_SERIAL_NUMBER}}{{MPAN_NUMBER}}_next_day_rates.

Since v9.0 now works in £ not pence I have changed default medium and high limits to 0.2 and 0.3 and rounding to 3 decimal places to show 1/10p.

It's my first attempt to push code via GitHub, so please be gentle ;-)

**Comment by igloo32** [comment] 2023-11-23 01:52
I must be been dense as I've never used github before but I've tried to submit a pull request with changes that make this work as before with the 3 new v9 "events" and add optional combine rates/show cheapest/use multiplier functions but it fails 
"Remote: Permission to lozzd/octopus-energy-rates-card.git denied"
"unable to access 'https://github.com/lozzd/octopus-energy-rates-card.git/': The requested URL returned error: 403"

**Comment by BottlecapDave** [comment] 2023-11-23 06:19
@igloo32 you need to fork the repo so you have read/write permissions. You then make the changes on your forked version of the repo. You then make a pull request from your repo (with your changes) to go into their repo

**Comment by igloo32** [comment] 2023-11-23 08:46
> @igloo32 you need to fork the repo so you have read/write permissions. You then make the changes on your forked version of the repo. You then make a pull request from your repo (with your changes) to go into their repo

Cheers - I switched to VS Code and it actually gave me a useful error message and solution.

**Comment by DJBenson** [comment] 2023-11-23 09:52
> > @igloo32 you need to fork the repo so you have read/write permissions. You then make the changes on your forked version of the repo. You then make a pull request from your repo (with your changes) to go into their repo
> 
> Cheers - I switched to VS Code and it actually gave me a useful error message and solution.

Great work! I've switched to your repo for now.

![image](https://github.com/lozzd/octopus-energy-rates-card/assets/1013909/9e51ae89-5aec-4b2f-8429-cddaf6dd0549)

**Comment by Daverover66** [comment] 2023-11-23 10:15
@DJBenson 
> Great work! I've switched to your repo for now.

How have you done that? I copied his forked code, but I can't find where the frontend custom elements are in HA?

**Comment by DJBenson** [comment] 2023-11-23 10:17
> @DJBenson
> 
> > Great work! I've switched to your repo for now.
> 
> How have you done that? I copied his forked code, but I can't find where the frontend custom elements are in HA?

I removed the existing version using HACS, added his GitHub repo as a custom repo, installed and updated the card config to include the three new entities as per the readme. When the original version gets fixed I'll just do the reverse, remove @igloo32 repo and switch back.

**Comment by lozzd** [comment] 2023-11-23 10:44
Thanks so much for the PRs here - I'll try and get this reviewed merged and released asap for all. Thanks again!

**Comment by RazorClam** [comment] 2023-11-23 12:05
> > @DJBenson
> > > Great work! I've switched to your repo for now.
> > 
> > 
> > How have you done that? I copied his forked code, but I can't find where the frontend custom elements are in HA?
> 
> I removed the existing version using HACS, added his GitHub repo as a custom repo, installed and updated the card config to include the three new entities as per the readme. When the original version gets fixed I'll just do the reverse, remove @igloo32 repo and switch back.

I do not seem to have those 3 entities.... what am i missing? I use the bottlecapdave octopus int

**Comment by mateuszdrab** [comment] 2023-11-23 12:12
> > > @DJBenson
> > > > Great work! I've switched to your repo for now.
> > > 
> > > 
> > > How have you done that? I copied his forked code, but I can't find where the frontend custom elements are in HA?
> > 
> > 
> > I removed the existing version using HACS, added his GitHub repo as a custom repo, installed and updated the card config to include the three new entities as per the readme. When the original version gets fixed I'll just do the reverse, remove @igloo32 repo and switch back.
> 
> I do not seem to have those 3 entities.... what am i missing? I use the bottlecapdave octopus int

You need to enable them as they're disabled by default in the integration settings

**Comment by RazorClam** [comment] 2023-11-23 12:22
> > > > @DJBenson
> > > > > Great work! I've switched to your repo for now.
> > > > 
> > > > 
> > > > How have you done that? I copied his forked code, but I can't find where the frontend custom elements are in HA?
> > > 
> > > 
> > > I removed the existing version using HACS, added his GitHub repo as a custom repo, installed and updated the card config to include the three new entities as per the readme. When the original version gets fixed I'll just do the reverse, remove @igloo32 repo and switch back.
> > 
> > 
> > I do not seem to have those 3 entities.... what am i missing? I use the bottlecapdave octopus int
> 
> You need to enable them as they're disabled by default in the integration settings

Perfect, just found that as you replied! Does it take a while to update? For me all 3 events return 'Unkonwn'

**Comment by corvus2606** [comment] 2023-11-23 13:07
> > > > > @DJBenson
> > > > > > Great work! I've switched to your repo for now.
> > > > > 
> > > > > 
> > > > > How have you done that? I copied his forked code, but I can't find where the frontend custom elements are in HA?
> > > > 
> > > > 
> > > > I removed the existing version using HACS, added his GitHub repo as a custom repo, installed and updated the card config to include the three new entities as per the readme. When the original version gets fixed I'll just do the reverse, remove @igloo32 repo and switch back.
> > > 
> > > 
> > > I do not seem to have those 3 entities.... what am i missing? I use the bottlecapdave octopus int
> > 
> > 
> > You need to enable them as they're disabled by default in the integration settings
> 
> Perfect, just found that as you replied! Does it take a while to update? For me all 3 events return 'Unkonwn'

They refresh every 30 minutes.

**Comment by Dave-Parry** [comment] 2023-11-24 12:40
would it possible to get this to display this he slots that are selected to be "on"?
Maybe a different ent colour?

**Comment by lozzd** [comment] 2023-11-24 13:54
Thanks again everyone - v0.3.0 has been released now. 
It's unfortunate those entities are disabled by default - I've mentioned that in the release notes. I think a clarification to the README will be neccessary also. 
I'm still waiting for mine to start working, reloading the integration isn't enough to trigger the "event" to make the rates load it seems.

**Comment by RazorClam** [comment] 2023-11-24 14:21
My card only goes to 10.30 tonight... is that expected behaviour?

**Comment by lozzd** [comment] 2023-11-24 14:22
Yes, for now anyway - tomorrow's rates aren't out yet. 

(Mine is now working as expected after the event fired)

**Comment by RazorClam** [comment] 2023-11-24 14:24
> Yes, for now anyway - tomorrow's rates aren't out yet.
> 
> (Mine is now working as expected after the event fired)

Perfect, thanks. Everything back to normal then. Thanks to all for getting this back going. It was my most used part of HA =)

**Comment by lozzd** [comment] 2023-11-24 14:27
As above, versus 0.3.0 is now out which resolves this.

**Closed** 2023-11-24 14:27 UTC
Labels: help wanted

**Comment by BottlecapDave** [comment] 2023-11-24 16:12
As of 9.0.1 the entities should be enabled by default, but I'm not sure if this will apply to people who installed the integration before this release.

**Comment by lozzd** [comment] 2023-11-24 18:30
I upgraded from 8.whatever straight to 9.0.1 and they were disabled. 
I updated the README already to explain how to enable them for now...

**Comment by Daverover66** [comment] 2023-11-24 18:32
Thanks to everyone who contributed to making this work again. Much appreciated!

**Comment by JRascagneres** [comment] 2023-11-25 03:29
I've updated it and added the rates to the config but I'm just seeing:
![image](https://github.com/lozzd/octopus-energy-rates-card/assets/3264971/1859e87b-a522-4498-9026-1617ddc928e2)

Any suggestions?
